import type { ScenarioDescriptor } from '../../shared/contracts.ts';

export const registry: ScenarioDescriptor[] = [
  {
    id: 'pos.inspect-cart',
    version: 1,
    effect: 'read-only',
    entry: 'test/specs/inspect-cart.spec.ts',
    parameterSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {},
      required: [],
    },
    requiredCapabilities: ['pos-native-read'],
    supportedAssertionModes: ['pos'],
  },
  {
    id: 'pos.inspect-screen',
    version: 1,
    effect: 'read-only',
    entry: 'test/specs/inspect-screen.spec.ts',
    parameterSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {},
      required: [],
    },
    requiredCapabilities: ['pos-native-read'],
    supportedAssertionModes: ['pos'],
  },
  {
    id: 'pos.inspect-product-search',
    version: 1,
    effect: 'read-only',
    entry: 'test/specs/inspect-product-search.spec.ts',
    parameterSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {},
      required: [],
    },
    requiredCapabilities: ['pos-native-read'],
    supportedAssertionModes: ['pos'],
  },
  {
    id: 'pos.inspect-order-actions',
    version: 1,
    effect: 'read-only',
    entry: 'test/specs/inspect-order-actions.spec.ts',
    parameterSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {},
      required: [],
    },
    requiredCapabilities: ['pos-native-read'],
    supportedAssertionModes: ['pos'],
  },
  {
    id: 'pos.inspect-return-surface',
    version: 1,
    effect: 'read-only',
    entry: 'test/specs/inspect-return-surface.spec.ts',
    parameterSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {},
      required: [],
    },
    requiredCapabilities: ['pos-native-read'],
    supportedAssertionModes: ['pos'],
  },
  {
    id: 'pos.navigate-home',
    version: 1,
    effect: 'read-only',
    entry: 'test/specs/navigate-home.spec.ts',
    parameterSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {},
      required: [],
    },
    requiredCapabilities: ['pos-native-read'],
    supportedAssertionModes: ['pos'],
  },
  {
    id: 'pos.inspect-location',
    version: 1,
    effect: 'read-only',
    entry: 'test/specs/inspect-location.spec.ts',
    parameterSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {},
      required: [],
    },
    requiredCapabilities: ['pos-native-read'],
    supportedAssertionModes: ['pos'],
  },
  {
    id: 'pos.open-first-order',
    version: 1,
    effect: 'read-only',
    entry: 'test/specs/open-first-order.spec.ts',
    parameterSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {},
      required: [],
    },
    requiredCapabilities: ['pos-native-read'],
    supportedAssertionModes: ['pos'],
  },
];
